name: benaiah_admin_app
description: Manage your furniture shop
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  badges: ^3.1.1
  bloc: ^8.1.2
  dartz: ^0.10.1
  desktop_drop: ^0.4.1
  device_preview: ^1.1.0
  dotted_border: ^2.0.0+3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_bloc: ^8.1.3
  flutter_layout_grid: ^2.0.3
  flutter_localizations:
    sdk: flutter
  flutter_platform_alert: ^0.4.0
  furniture_store_server_client:
    path: ./client/furniture_store_server_client
  get_it: ^7.6.0
  http: ^0.13.5
  iconly: ^1.0.1
  image_picker: ^0.8.9
  intl: ^0.18.0
  lottie: ^2.4.0
  provider: ^6.0.5
  responsive_framework: ^1.0.0
  serverpod_flutter: ^1.1.1
  syncfusion_flutter_datagrid: ^22.2.9
  uuid: ^3.0.7
  window_manager: ^0.3.4
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/lottie/
    - assets/icons/
    - assets/images/
